tutorus/step/urls.py
from django.conf.urls import patterns, include, url
from .views import add, edit, delete

urlpatterns = patterns('',
    url(r'^add/(?P<classroom_id>\w+)/$', add, name='step_add'),
    url(r'^(?P<classroom_id>\w+)/delete/(?P<step_id>\w+)$', delete, name='step_delete'),
    url(r'^(?P<classroom_id>\w+)/edit/(?P<step_id>\w+)$', edit, name='step_edit'),
)

tutorus/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from user.forms import SignupFormExtra

urlpatterns = patterns(
    '',
    url(r'^$', 'core.views.home', name='home'),
    url(r'^classroom/', include('classroom.urls')),
    url(r'^question/', include('questions.urls')),
    # Override the signup form with our own, which includes a first and last name.
    (r'^accounts/signup/$', 'userena.views.signup', {'signup_form': SignupFormExtra}),
    (r'^accounts/', include('userena.urls')),
    (r'^messages/', include('userena.contrib.umessages.urls')),
    (r'^class/', include('classroom.urls')),
    (r'^step/', include('step.urls')),
    (r'^suggest/', include('suggest.urls')),
)

urlpatterns += staticfiles_urlpatterns()

tutorus/step/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from classroom.models import ClassRoom


class Step(models.Model):
    """ Steps for a ClassRoom
    """
    name = models.CharField(_('name'), max_length=50, blank=True)
    step_order = models.PositiveSmallIntegerField()
    content = models.TextField(blank=True, null=True, default="")
    classroom = models.ForeignKey(ClassRoom)

tutorus/step/forms.py
from django.forms import ModelForm, CharField, HiddenInput
from .models import Step

class StepForm(ModelForm):
    name = CharField(required=True)
    content = CharField(widget=HiddenInput())

    class Meta:
        model = Step
        exclude = ('classroom','step_order')

    def save(self, classroom, commit=True):
        step= super(StepForm, self).save(commit=False)
        step.classroom = classroom
        step.step_order = 1 #todo, fix this.
        step.save()

        return step
        

tutorus/step/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from classroom.models import ClassRoom
from .models import Step
from .forms import StepForm
from django.contrib.auth.decorators import login_required


@login_required
def add(request, classroom_id):
    """
    add Step to classroom
    """
    #TODO do a 404 check here.
    classroom = ClassRoom.objects.get(pk=classroom_id)
    
    if request.method == 'POST':
        form = StepForm(request.POST)
        if form.is_valid():
            try:
                step = form.save(classroom)            
                return HttpResponseRedirect(reverse('class_create_step', args=[classroom.pk]))
            except Exception as e:
                #TODO: fix me.
                print("ERROR {0}".format(e))
        else:
            print form
    else:
        form = StepForm()

    context = {'form':form, 'classroom': classroom}
    return render(request, 'step/add.html', context)
    
@login_required
def edit(request, classroom_id, step_id):
    """
    add Step to classroom
    """
    #TODO do a 404 check here.
    classroom = ClassRoom.objects.get(pk=classroom_id)
    step = Step.objects.get(pk=step_id)

    if request.method == 'POST':
        form = StepForm(request.POST, instance=step)
        if form.is_valid():
            try:
                step = form.save(classroom)            
                return HttpResponseRedirect(reverse('class_create_step', args=[classroom.pk]))
            except Exception as e:
                #TODO: fix me.
                print("ERROR {0}".format(e))
        else:
            print form
    else:
        form = StepForm(instance=step)

    context = {'form':form, 'classroom': classroom}
    return render(request, 'step/add.html', context)
    
    
@login_required
def delete(request, classroom_id, step_id):
    """
    delete Step from classroom
    """
    #TODO do a 404 check here.
    classroom = ClassRoom.objects.get(pk=classroom_id)
    step = Step.objects.filter(pk=step_id).delete()

    return HttpResponseRedirect(reverse('class_create_step', args=[classroom.pk]))

tutorus/step/templates/step/add.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Add Step" %}{% endblock %}


{% block page-js %}
    <script src="{{ STATIC_URL }}epiceditor/js/epiceditor.min.js"></script>
    <script type="text/javascript">
    var opts = {
  container: 'epiceditor',
  basePath: '{{ STATIC_URL }}epiceditor',
  parser: marked,
  clientSideStorage: false,
  theme: {
    base:'/themes/base/epiceditor.css',
    preview:'/themes/preview/preview-dark.css',
    editor:'/themes/editor/epic-dark.css'
  },
  shortcut: {
    modifier: 18,
    fullscreen: 70,
    preview: 80,
    edit: 79
  }
}
var editor = new EpicEditor(opts).load();
    
    
  $(document).ready(function(){
    
    editor.importFile('some-file',$("#id_content").val());
    

    var validator = $("#add_step_form").validate({
      rules: {
        name: "required"
      },
      highlight: function(label) {
          $(label).closest('.control-group').addClass('error');
      },
      success: function(label) {
        label
        .text('OK!').addClass('valid')
       .closest('.control-group').addClass('success');
      }
    });

    $('#save_button').click(function() {
        var theContent = editor.exportFile(null,'html');
        $("#id_content").val(theContent);
        validator.resetForm(); 
   });
   
    $('#cancel_button').click(function() {
        validator.resetForm(); 
   });
     
    
  });
  </script>

{% endblock page-js %}

{% block content %}
{{ form.non_field_errors }}

<form id="add_step_form" class="form-horizontal" action="" enctype="multipart/form-data" method="post">
  <fieldset>
    <legend>Add Step to {{classroom.name}}</legend>
    <div class="control-group {%if form.name.errors %}error{% endif %}">
      <label class="control-label" for="input01">*Step Name</label>
      <div class="controls">
        {{form.name}}
        <span class="help-inline">{{form.name.errors}}</span>
      </div>
    </div>
    
    <div class="control-group">
      <label class="control-label" for="input01">Content (markdown)</label>
      <div class="controls">
        <div id="epiceditor"></div>
        {{form.content}}
        <p class="help-block"></p>
      </div>
    </div>
    <div class="form-actions">
            <button type="submit" class="btn btn-primary" id='save_button'>Save changes</button>
            <a class="btn" id="cancel_button" href='{% url class_create_step classroom.pk %}'>Cancel</a>
    </div>
  </fieldset>

{% csrf_token %}
</form>
{% endblock %}